### ISSUE TITLE
Payment not happening

### ISSUE THREAD

**Issue by Abhandari6** [Jaimin25/Sahyog#5]
it shows "We are unable to authenticate your payment method. Please choose a different payment method and try again."
@Jaimin25

**Comment by Jaimin25** [comment]
Payments are taking place in test mode, so you need to use this details which is provided by stripe officialy to make testing payments

![image](https://github.com/user-attachments/assets/3e3f62ff-27eb-40c9-bc3b-3bc825da1060)

**Comment by jamnxdev** [comment]
> it shows "We are unable to authenticate your payment method. Please choose a different payment method and try again." @Jaimin25

Payments are taking place in test mode, so you need to use this details which is provided by stripe officialy to make testing payments
![Screenshot from 2024-07-20 16-44-27](https://github.com/user-attachments/assets/58dd14c3-3629-4273-add1-58f3a239c98e)
